# docker-compose.yml
services:
    booklogr-api:
        container_name: "booklogr-api"
        image: mozzo/booklogr:v1.5.0
        environment:
            - DATABASE_URL=sqlite:///books.db
            - AUTH_SECRET_KEY=this-really-needs-to-be-changed
        ports:
            - 5000:5000
        volumes:
            - ./data:/app/instance

    booklogr-web:
        container_name: "booklogr-web"
        image: mozzo/booklogr-web:v1.5.0
        environment:
            - BL_API_ENDPOINT=http://localhost:5000/ # CHANGE THIS TO POINT TO THE EXTERNAL ADRESS THE USER CAN ACCESS
            - BL_GOOGLE_ID= # Leave empty to disable google login. To enable, write in your Google Client ID.
            - BL_DISABLE_HOMEPAGE=true
            - BL_DEMO_MODE=false
        ports:
            - 5150:80