# docker-compose.yml
services:
    booklogr-db:
        container_name: "booklogr-db"
        image: "postgres" # use latest official postgres version
        ports:
            - 5432:5432  
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
            interval: 10s
            timeout: 5s
            retries: 5
        env_file:
            - .env
        volumes:
            - booklogr:/var/lib/postgresql/db-data/ # persist data even if container shuts down

    booklogr-api:
        container_name: "booklogr-api"
        image: mozzo/booklogr:latest
        depends_on:
            booklogr-db:
              condition: service_healthy
        env_file:
            - .env
        ports:
            - 5000:5000

    auth-api:
        container_name: "auth-server-api"
        image: mozzo/auth-server:1.0.0
        restart: always
        volumes:
            - auth_db_vol:/app/instance
        environment:
            DATABASE_URL: "sqlite:///users.db" # CHANGE THIS FOR USE IN PRODUCTION! Needs to be the same as the credentials in auth-db
        env_file:
            - .env
        ports:
            - 5001:5000

volumes:
    booklogr:
    auth-server:
    auth_db_vol: