"""Add rating column

Revision ID: 334c6f93b980
Revises: 4f342e92ab1f
Create Date: 2024-07-15 17:46:55.556749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334c6f93b980'
down_revision = '4f342e92ab1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
