"""Add subtitle column to books table

Revision ID: 37f4bd40ba32
Revises: 85ac23ba45cb
Create Date: 2026-06-27 20:53:40.847375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f4bd40ba32'
down_revision = '85ac23ba45cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('subtitle')

    # ### end Alembic commands ###
