"""Add files table

Revision ID: 82989182da4a
Revises: 9232f4adc495
Create Date: 2024-07-26 19:30:06.488079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82989182da4a'
down_revision = '9232f4adc495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
