"""Add owner_id column

Revision ID: ae48d4b4f9d8
Revises: e60887c12d97
Create Date: 2024-06-30 16:43:58.045264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae48d4b4f9d8'
down_revision = 'e60887c12d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
