"""Add quote_page column to notes table

Revision ID: c9e06189519a
Revises: 89b6827408dd
Create Date: 2024-12-27 14:15:32.832448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e06189519a'
down_revision = '89b6827408dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quote_page', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('quote_page')

    # ### end Alembic commands ###
